#%RAML 0.8
---
title: BeerCoders API
baseUri: http://api.beercoders.pl
mediaType: application/json
version: v1
securedBy: [oauth_2_0]
protocols:
  - HTTP
  - HTTPS

schemas:
 - article: !include schemas/article.schema

securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth2.yml

resourceTypes:
  - collection: !include resourceTypes/collection.yml
  - collection-item: !include resourceTypes/collection-item.yml

traits:
  - orderable: !include traits/orderable.yml
  - pageable: !include traits/pageable.yml
  - searchable: !include traits/searchable.yml

/articles:
  type:
    collection:
      exampleCollection: !include examples/articles.sample
      exampleItem: !include examples/article.sample
      exampleBody: !include examples/article-new.sample
  get:
    is: [
          searchable: {description: "with valid searchable fields: title", example: "[\"title\", \"Get L\", \"like\"]"},
          orderable: {fieldsList: "title"},
          pageable
        ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/article.sample
        exampleBody: !include examples/article-new.sample
