#%RAML 1.0
---
title: BeerCoders API
baseUri: http://api.beercoders.pl
mediaType: application/json
version: v1
protocols: [ HTTP, HTTPS ]
securedBy: [ oauth_2_0 ]

securitySchemes:
  oauth_2_0: !include securitySchemes/oauth2.raml

documentation:
 - title: Legal
   content: !include documentation/legal.markdown

uses:
 article: libraries/article.raml

 /articles:
   type:
     collection:
       exampleCollection: !include examples/articles.json
       exampleItem: !include examples/article.json
       typeItem: article.Article
       typeCollection: article.Articles
   get:
     is: [
           searchable: {description: "with valid searchable fields: title", example: "[\"title\", \"Get L\", \"like\"]"},
           orderable: {fieldsList: "title"},
           pageable
         ]
   /{id}:
     type:
       collection-item:
         exampleCollection: !include examples/articles.json
         exampleItem: !include examples/article.json
         typeItem: article.Article
         typeCollection: article.Articles
