#%RAML 1.0 ResourceType
description: Collection of available <<resourcePathName>>.
get:
  description: Get a list of <<resourcePathName>>.
  responses:
    200:
      body:
        type: <<typeCollection>>
        example: <<exampleCollection>>
post:
  description: Create/add a new <<resourcePathName|!singularize>>.
  body:
    type: <<typeItem>>
    example: <<exampleItem>>
  responses:
    201:
      headers:
        Location:
      body:
        type: <<typeItem>>
        example: <<exampleItem>>
